name: Deployment

on:
  push:
    branches: [hexo]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true  # 这个会拉取 butterfly 主题

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        # 安装与 hexo 7.3.0 兼容的 hexo-cli 版本
        npm i -g hexo-cli@4.3.2
        npm i
        hexo clean
        hexo generate
        
    - name: Deploy to Github Pages
      env:
        GIT_NAME: isrror
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/isrror/isrror.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master